---
title: "Practice 2.2"
author: "Fishcan"
date: "2023-09-22"
output: html_document
---

VD: Good, well done. This is just a comment to learn to accept outside 'push' / edit. Try to merge this comment in GitHub, pull in RStudio, delete it, commit and push back.  

## Import the data set
```{r}
rairuoho <- read.table(
  'https://www.dipintothereef.com/uploads/3/7/3/5/37359245/rairuoho.txt',
  header=T, sep="\t", dec=".", na.strings = "n/a")
head(rairuoho)
```

## Load some packages
```{r}
library(dplyr) 
library(tidyr)
```

## Modify the table and generate new data set
```{r}
rairuoho2 <- rairuoho %>% 
  #Replace nutrient with enriched
  mutate(treatment = 
         ifelse(treatment == "nutrient",
                "enriched",treatment)) %>%
  #Reformat the table
  pivot_longer(cols=c(1:6), 
               names_to = "day", 
               values_to = "length") %>%
  #Merge variables Spatial1 and Spatial2
  unite("spatial", 
        c(spatial1,spatial2), 
        sep = "_") %>%
  #Remove variables row and column
  dplyr::select(-c(row,column))

rairuoho2
```
